---
- name: Ensure Pip is installed
  ansible.builtin.package:
    name: "{{ pip_package }}"
    state: present

- name: Get installed python3 version
  ansible.builtin.shell: python3 --version | awk '{split($2, a, "."); print a[1] "." a[2]}'
  register: python3_version
  changed_when: false

- name: Get installed pip version
  ansible.builtin.shell: "{{ pip_executable }} --version | awk '{split($2, a, \".\"); print a[1] \".\" a[2] \".\" a[3]}'"
  register: pip_version
  changed_when: false

- name: Set facts
  set_fact:
    pip_externally_managed: "{{ python3_version.stdout is version_compare('3.11', '>=') }}"
    pip_break_system_packages_support: "{{ pip_version.stdout is version_compare('23.0.1', '>=') }}"
  when: python3_version is defined and pip_version is defined

- include_tasks: pip-modern.yml
  when: ansible_version.full is version_compare('2.17', '>=')

- include_tasks: pip-legacy.yml
  when: ansible_version.full is version_compare('2.17', '<')
