- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    extra_args: "{{ '--break-system-packages' if pip_break_system_packages_support and item.break_system_packages | default(false) else omit }}"
    executable: "{{ item.virtualenv | default(false) | ternary(omit, pip_executable) }}"
  loop: "{{ pip_install_packages }}"
